server:
  port: # Enter web services port number
  error:
    whitelabel:
      enabled: true
spring:
  datasource:
    password: # Enter password of the database
    username: # Enter username of the database
    url: # Enter database URL
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: # Enter username of the database
      password: # Enter password of the database
  mvc:
    servlet:
      path: /
  kafka:
    bootstrap-servers: #Enter Kafka ip and port
api:
  key: # Enter API Key for the ExchangeRate-API
