server:
  port: 8082
  error:
    whitelabel:
      enabled: true
spring:
  application:
    name: mpba-api
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  security:
    user:
      name: postgres
      password: postgres
  mvc:
    servlet:
      path: /
  kafka:
    bootstrap-servers: localhost:9092
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    default-schema: public
    user: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
api:
  key: 2d03edf7aa4c0318731708ae
security:
  jwt:
    secret-key: 7d9e1b591dfcbcf28483189062bf531ad8a06702062601784c7f1f6e75566b78
    expiration-time: 3600000