server:
  port: 8082
  error:
    whitelabel:
      enabled: true
spring:
  datasource:
    password: # enter your password here
    username: # enter your username here
    url: # enter your url here
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  security:
    user:
      name: # enter your username here
      password: # enter your password here
  mvc:
    servlet:
      path: /
  kafka:
    bootstrap-servers: localhost:9092
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    default-schema: public
    url: # enter you database url here
    user: # enter your database username here
    password: # enter your database password here
    driver-class-name: org.postgresql.Driver
api:
  key: # enter your api key here
security:
  jwt:
    # plain text: cvutfelsit2025, key: dmitriyrastvorov
    secret-key: # enter your secret key here
    expiration-time: 3600000